import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import{ChevronLeft,ChevronRight,X}from'lucide-react';import'./style.css';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const pad=n=>String(n).padStart(2,'0');const ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const hm=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`;const addDays=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};const monday=d=>{let x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};const slots=Array.from({length:48},(_,i)=>`${pad(Math.floor(i/2))}:${i%2?'30':'00'}`);const KST='+09:00';
function App(){const[week,setWeek]=useState(monday(new Date()));const[rs,setRs]=useState([]);const[modal,setModal]=useState(null);const[err,setErr]=useState('');const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(week,i)),[week]);const today=new Date();today.setHours(0,0,0,0);const max=addDays(today,30);
async function load(){let a=week.toISOString(),b=addDays(week,7).toISOString();const{data,error}=await supabase.from('reservations').select('*').lt('start_at',b).gt('end_at',a).order('start_at');if(error)setErr(error.message);else setRs(data||[])}useEffect(()=>{load()},[week]);
const dateAt=(d,t)=>new Date(`${ymd(d)}T${t}:00${KST}`);const occupying=(d,t)=>{let s=dateAt(d,t),e=new Date(s.getTime()+30*60000);return rs.find(r=>new Date(r.start_at)<e&&new Date(r.end_at)>s)};
async function reserve(e){e.preventDefault();setErr('');let fd=new FormData(e.currentTarget),start=dateAt(modal.day,fd.get('start'));let endDay=fd.get('end')<=fd.get('start')?addDays(modal.day,1):modal.day,end=dateAt(endDay,fd.get('end'));const duration=end-start;if(duration>90*60*1000){setErr('한 번에 최대 1시간 30분까지만 예약할 수 있습니다.');return}if(start<new Date()){setErr('지난 시간은 예약할 수 없습니다.');return}if(start>max){setErr('오늘부터 30일 이내만 예약할 수 있습니다.');return}const{data:overlap}=await supabase.from('reservations').select('id').lt('start_at',end.toISOString()).gt('end_at',start.toISOString()).limit(1);if(overlap?.length){setErr('이미 예약된 시간이 포함되어 있습니다.');return}const{error}=await supabase.from('reservations').insert({team_name:fd.get('team').trim(),start_at:start.toISOString(),end_at:end.toISOString(),password:fd.get('pw')});if(error)setErr(error.message);else{setModal(null);load()}}
function open(d,t){if(d<today||d>max)return;setErr('');setModal({day:d,start:t})}
return <><header><div><h1>합주실 예약</h1><p>30분 단위 · 24시간 운영</p></div><button onClick={()=>setWeek(monday(new Date()))}>이번 주</button></header><main><div className="nav"><button onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft/></button><strong>{week.getMonth()+1}월 {week.getDate()}일 — {days[6].getMonth()+1}월 {days[6].getDate()}일</strong><button onClick={()=>setWeek(addDays(week,7))}><ChevronRight/></button></div><div className="hint">빈 시간을 눌러 예약하세요 · 1회 최대 1시간 30분 · 오늘부터 30일 이내 예약 가능</div>{err&&!modal&&<p className="error">{err}</p>}<div className="calendar"><div className="corner">시간</div>{days.map(d=><div className={'day '+(ymd(d)===ymd(new Date())?'today':'')} key={ymd(d)}><b>{['일','월','화','수','목','금','토'][d.getDay()]}</b><span>{d.getMonth()+1}/{d.getDate()}</span></div>)}{slots.map(t=><React.Fragment key={t}><div className="time">{t}</div>{days.map(d=>{let r=occupying(d,t);let isStart=r&&hm(new Date(r.start_at))===t&&ymd(new Date(r.start_at))===ymd(d);return <button key={ymd(d)+t} className={'cell '+(r?'booked':'')+(d<today||d>max?' disabled':'')} onClick={()=>r?setModal({reservation:r}):open(d,t)}>{isStart?<><b>{r.team_name}</b><small>{hm(new Date(r.start_at))}–{hm(new Date(r.end_at))}</small></>:''}</button>})}</React.Fragment>)}</div></main>{modal&&<div className="shade" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal.reservation?<Cancel r={modal.reservation} done={()=>{setModal(null);load()}}/>:<><h2>합주실 예약</h2><p className="sub">{modal.day.getMonth()+1}월 {modal.day.getDate()}일</p><form onSubmit={reserve}><label>팀명<input name="team" required maxLength="30" placeholder="예: A팀"/></label><div className="row"><label>시작<select name="start" defaultValue={modal.start}>{slots.map(x=><option>{x}</option>)}</select></label><label>종료<select name="end" defaultValue={slots[(slots.indexOf(modal.start)+2)%48]}>{[1,2,3].map(n=>{const i=(slots.indexOf(modal.start)+n)%48;return <option key={n} value={slots[i]}>{slots[i]}</option>})}</select></label></div><label>취소 암호<input name="pw" required type="password" minLength="4" placeholder="4자리 이상"/></label>{err&&<p className="error">{err}</p>}<button className="primary">예약하기</button></form></>}</div></div>}</>}
function Cancel({r,done}){const[pw,setPw]=useState('');const[msg,setMsg]=useState('');async function cancel(){if(pw!==r.password){setMsg('암호가 일치하지 않습니다.');return}setMsg('현재 DB 보안 설정상 취소 기능은 다음 단계에서 활성화합니다.');}return <><h2>{r.team_name}</h2><p className="sub">{new Date(r.start_at).toLocaleString('ko-KR')} ~ {new Date(r.end_at).toLocaleString('ko-KR')}</p><label>취소 암호<input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="예약 시 설정한 암호"/></label>{msg&&<p className="error">{msg}</p>}<button className="danger" onClick={cancel}>예약 취소</button></>}
createRoot(document.getElementById('root')).render(<App/>);
